### ISSUE TITLE
Having trouble connecting to instrument

### ISSUE THREAD

**Issue by jsbreakfield** [AFMD/mppTracker#16]
I keep getting errors that say,

Error 1 (using pyvisa-py backend):
module 'visa' has no attribute 'ResourceManager'
Error 2 (using pyvisa default backend):
module 'visa" has no attribute 'ResourceManager'

I am not sure what to do. I would also like to say that the Keithley is attached with rs232

**Comment by ilario** [comment]
Hi!
Here they suggest to replace "visa" by "pyvisa": https://github.com/pyvisa/pyvisa/issues/447
Try that and let us know.

**Comment by ilario** [comment]
But even if it works, seems that the original developer abandoned this project in 2018, so I would suggest forking it if you want to modify the public code. If you go on with the development, please announce that in an issue on this repository. Thanks!

**Comment by greyltc** [comment]
Hey, I've continued development of my mppt code over here: https://github.com/greyltc/centralcontrol/blob/master/src/centralcontrol/mppt.py

**Comment by ilario** [comment]
Ah! Great!! Can you write this in a huge font in the readme of this repository? Thanks!

**Comment by jsbreakfield** [comment]
> Hi! Here they suggest to replace "visa" by "pyvisa": [pyvisa/pyvisa#447](https://github.com/pyvisa/pyvisa/issues/447) Try that and let us know.

Looking through this resource helped! I changed the 'import visa' line in the mppTracker file to 'import pyvisa as visa' and now I am able to connect to the Keithley. Thank you so much!
